<?php
/**
 * ApplicationServiceGroupEffectiveRatesMirModcodTable
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iVantage API
 *
 * This is the iDirect iVantage API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * ApplicationServiceGroupEffectiveRatesMirModcodTable Class Doc Comment
 *
 * @category    Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ApplicationServiceGroupEffectiveRatesMirModcodTable implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'ApplicationServiceGroup_EffectiveRates_MirModcodTable';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'mc_qpsk_1_4' => 'double',
        'mc_qpsk_1_3' => 'double',
        'mc_qpsk_2_5' => 'double',
        'mc_qpsk_1_2' => 'double',
        'mc_qpsk_3_5' => 'double',
        'mc_qpsk_2_3' => 'double',
        'mc_qpsk_3_4' => 'double',
        'mc_qpsk_4_5' => 'double',
        'mc_qpsk_5_6' => 'double',
        'mc_qpsk_8_9' => 'double',
        'mc_qpsk_9_10' => 'double',
        'mc_8_psk_3_5' => 'double',
        'mc_8_psk_2_3' => 'double',
        'mc_8_psk_3_4' => 'double',
        'mc_8_psk_5_6' => 'double',
        'mc_8_psk_8_9' => 'double',
        'mc_8_psk_9_10' => 'double',
        'mc_16_apsk_2_3' => 'double',
        'mc_16_apsk_3_4' => 'double',
        'mc_16_apsk_4_5' => 'double',
        'mc_16_apsk_5_6' => 'double',
        'mc_16_apsk_8_9' => 'double',
        'mc_16_apsk_9_10' => 'double',
        'mc_32_apsk_3_4' => 'double',
        'mc_32_apsk_4_5' => 'double',
        'mc_32_apsk_5_6' => 'double',
        'mc_32_apsk_8_9' => 'double',
        'mc_32_apsk_9_10' => 'double'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'mc_qpsk_1_4' => 'double',
        'mc_qpsk_1_3' => 'double',
        'mc_qpsk_2_5' => 'double',
        'mc_qpsk_1_2' => 'double',
        'mc_qpsk_3_5' => 'double',
        'mc_qpsk_2_3' => 'double',
        'mc_qpsk_3_4' => 'double',
        'mc_qpsk_4_5' => 'double',
        'mc_qpsk_5_6' => 'double',
        'mc_qpsk_8_9' => 'double',
        'mc_qpsk_9_10' => 'double',
        'mc_8_psk_3_5' => 'double',
        'mc_8_psk_2_3' => 'double',
        'mc_8_psk_3_4' => 'double',
        'mc_8_psk_5_6' => 'double',
        'mc_8_psk_8_9' => 'double',
        'mc_8_psk_9_10' => 'double',
        'mc_16_apsk_2_3' => 'double',
        'mc_16_apsk_3_4' => 'double',
        'mc_16_apsk_4_5' => 'double',
        'mc_16_apsk_5_6' => 'double',
        'mc_16_apsk_8_9' => 'double',
        'mc_16_apsk_9_10' => 'double',
        'mc_32_apsk_3_4' => 'double',
        'mc_32_apsk_4_5' => 'double',
        'mc_32_apsk_5_6' => 'double',
        'mc_32_apsk_8_9' => 'double',
        'mc_32_apsk_9_10' => 'double'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'mc_qpsk_1_4' => 'MC_QPSK_1_4',
        'mc_qpsk_1_3' => 'MC_QPSK_1_3',
        'mc_qpsk_2_5' => 'MC_QPSK_2_5',
        'mc_qpsk_1_2' => 'MC_QPSK_1_2',
        'mc_qpsk_3_5' => 'MC_QPSK_3_5',
        'mc_qpsk_2_3' => 'MC_QPSK_2_3',
        'mc_qpsk_3_4' => 'MC_QPSK_3_4',
        'mc_qpsk_4_5' => 'MC_QPSK_4_5',
        'mc_qpsk_5_6' => 'MC_QPSK_5_6',
        'mc_qpsk_8_9' => 'MC_QPSK_8_9',
        'mc_qpsk_9_10' => 'MC_QPSK_9_10',
        'mc_8_psk_3_5' => 'MC_8PSK_3_5',
        'mc_8_psk_2_3' => 'MC_8PSK_2_3',
        'mc_8_psk_3_4' => 'MC_8PSK_3_4',
        'mc_8_psk_5_6' => 'MC_8PSK_5_6',
        'mc_8_psk_8_9' => 'MC_8PSK_8_9',
        'mc_8_psk_9_10' => 'MC_8PSK_9_10',
        'mc_16_apsk_2_3' => 'MC_16APSK_2_3',
        'mc_16_apsk_3_4' => 'MC_16APSK_3_4',
        'mc_16_apsk_4_5' => 'MC_16APSK_4_5',
        'mc_16_apsk_5_6' => 'MC_16APSK_5_6',
        'mc_16_apsk_8_9' => 'MC_16APSK_8_9',
        'mc_16_apsk_9_10' => 'MC_16APSK_9_10',
        'mc_32_apsk_3_4' => 'MC_32APSK_3_4',
        'mc_32_apsk_4_5' => 'MC_32APSK_4_5',
        'mc_32_apsk_5_6' => 'MC_32APSK_5_6',
        'mc_32_apsk_8_9' => 'MC_32APSK_8_9',
        'mc_32_apsk_9_10' => 'MC_32APSK_9_10'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'mc_qpsk_1_4' => 'setMcQpsk14',
        'mc_qpsk_1_3' => 'setMcQpsk13',
        'mc_qpsk_2_5' => 'setMcQpsk25',
        'mc_qpsk_1_2' => 'setMcQpsk12',
        'mc_qpsk_3_5' => 'setMcQpsk35',
        'mc_qpsk_2_3' => 'setMcQpsk23',
        'mc_qpsk_3_4' => 'setMcQpsk34',
        'mc_qpsk_4_5' => 'setMcQpsk45',
        'mc_qpsk_5_6' => 'setMcQpsk56',
        'mc_qpsk_8_9' => 'setMcQpsk89',
        'mc_qpsk_9_10' => 'setMcQpsk910',
        'mc_8_psk_3_5' => 'setMc8Psk35',
        'mc_8_psk_2_3' => 'setMc8Psk23',
        'mc_8_psk_3_4' => 'setMc8Psk34',
        'mc_8_psk_5_6' => 'setMc8Psk56',
        'mc_8_psk_8_9' => 'setMc8Psk89',
        'mc_8_psk_9_10' => 'setMc8Psk910',
        'mc_16_apsk_2_3' => 'setMc16Apsk23',
        'mc_16_apsk_3_4' => 'setMc16Apsk34',
        'mc_16_apsk_4_5' => 'setMc16Apsk45',
        'mc_16_apsk_5_6' => 'setMc16Apsk56',
        'mc_16_apsk_8_9' => 'setMc16Apsk89',
        'mc_16_apsk_9_10' => 'setMc16Apsk910',
        'mc_32_apsk_3_4' => 'setMc32Apsk34',
        'mc_32_apsk_4_5' => 'setMc32Apsk45',
        'mc_32_apsk_5_6' => 'setMc32Apsk56',
        'mc_32_apsk_8_9' => 'setMc32Apsk89',
        'mc_32_apsk_9_10' => 'setMc32Apsk910'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'mc_qpsk_1_4' => 'getMcQpsk14',
        'mc_qpsk_1_3' => 'getMcQpsk13',
        'mc_qpsk_2_5' => 'getMcQpsk25',
        'mc_qpsk_1_2' => 'getMcQpsk12',
        'mc_qpsk_3_5' => 'getMcQpsk35',
        'mc_qpsk_2_3' => 'getMcQpsk23',
        'mc_qpsk_3_4' => 'getMcQpsk34',
        'mc_qpsk_4_5' => 'getMcQpsk45',
        'mc_qpsk_5_6' => 'getMcQpsk56',
        'mc_qpsk_8_9' => 'getMcQpsk89',
        'mc_qpsk_9_10' => 'getMcQpsk910',
        'mc_8_psk_3_5' => 'getMc8Psk35',
        'mc_8_psk_2_3' => 'getMc8Psk23',
        'mc_8_psk_3_4' => 'getMc8Psk34',
        'mc_8_psk_5_6' => 'getMc8Psk56',
        'mc_8_psk_8_9' => 'getMc8Psk89',
        'mc_8_psk_9_10' => 'getMc8Psk910',
        'mc_16_apsk_2_3' => 'getMc16Apsk23',
        'mc_16_apsk_3_4' => 'getMc16Apsk34',
        'mc_16_apsk_4_5' => 'getMc16Apsk45',
        'mc_16_apsk_5_6' => 'getMc16Apsk56',
        'mc_16_apsk_8_9' => 'getMc16Apsk89',
        'mc_16_apsk_9_10' => 'getMc16Apsk910',
        'mc_32_apsk_3_4' => 'getMc32Apsk34',
        'mc_32_apsk_4_5' => 'getMc32Apsk45',
        'mc_32_apsk_5_6' => 'getMc32Apsk56',
        'mc_32_apsk_8_9' => 'getMc32Apsk89',
        'mc_32_apsk_9_10' => 'getMc32Apsk910'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['mc_qpsk_1_4'] = isset($data['mc_qpsk_1_4']) ? $data['mc_qpsk_1_4'] : null;
        $this->container['mc_qpsk_1_3'] = isset($data['mc_qpsk_1_3']) ? $data['mc_qpsk_1_3'] : null;
        $this->container['mc_qpsk_2_5'] = isset($data['mc_qpsk_2_5']) ? $data['mc_qpsk_2_5'] : null;
        $this->container['mc_qpsk_1_2'] = isset($data['mc_qpsk_1_2']) ? $data['mc_qpsk_1_2'] : null;
        $this->container['mc_qpsk_3_5'] = isset($data['mc_qpsk_3_5']) ? $data['mc_qpsk_3_5'] : null;
        $this->container['mc_qpsk_2_3'] = isset($data['mc_qpsk_2_3']) ? $data['mc_qpsk_2_3'] : null;
        $this->container['mc_qpsk_3_4'] = isset($data['mc_qpsk_3_4']) ? $data['mc_qpsk_3_4'] : null;
        $this->container['mc_qpsk_4_5'] = isset($data['mc_qpsk_4_5']) ? $data['mc_qpsk_4_5'] : null;
        $this->container['mc_qpsk_5_6'] = isset($data['mc_qpsk_5_6']) ? $data['mc_qpsk_5_6'] : null;
        $this->container['mc_qpsk_8_9'] = isset($data['mc_qpsk_8_9']) ? $data['mc_qpsk_8_9'] : null;
        $this->container['mc_qpsk_9_10'] = isset($data['mc_qpsk_9_10']) ? $data['mc_qpsk_9_10'] : null;
        $this->container['mc_8_psk_3_5'] = isset($data['mc_8_psk_3_5']) ? $data['mc_8_psk_3_5'] : null;
        $this->container['mc_8_psk_2_3'] = isset($data['mc_8_psk_2_3']) ? $data['mc_8_psk_2_3'] : null;
        $this->container['mc_8_psk_3_4'] = isset($data['mc_8_psk_3_4']) ? $data['mc_8_psk_3_4'] : null;
        $this->container['mc_8_psk_5_6'] = isset($data['mc_8_psk_5_6']) ? $data['mc_8_psk_5_6'] : null;
        $this->container['mc_8_psk_8_9'] = isset($data['mc_8_psk_8_9']) ? $data['mc_8_psk_8_9'] : null;
        $this->container['mc_8_psk_9_10'] = isset($data['mc_8_psk_9_10']) ? $data['mc_8_psk_9_10'] : null;
        $this->container['mc_16_apsk_2_3'] = isset($data['mc_16_apsk_2_3']) ? $data['mc_16_apsk_2_3'] : null;
        $this->container['mc_16_apsk_3_4'] = isset($data['mc_16_apsk_3_4']) ? $data['mc_16_apsk_3_4'] : null;
        $this->container['mc_16_apsk_4_5'] = isset($data['mc_16_apsk_4_5']) ? $data['mc_16_apsk_4_5'] : null;
        $this->container['mc_16_apsk_5_6'] = isset($data['mc_16_apsk_5_6']) ? $data['mc_16_apsk_5_6'] : null;
        $this->container['mc_16_apsk_8_9'] = isset($data['mc_16_apsk_8_9']) ? $data['mc_16_apsk_8_9'] : null;
        $this->container['mc_16_apsk_9_10'] = isset($data['mc_16_apsk_9_10']) ? $data['mc_16_apsk_9_10'] : null;
        $this->container['mc_32_apsk_3_4'] = isset($data['mc_32_apsk_3_4']) ? $data['mc_32_apsk_3_4'] : null;
        $this->container['mc_32_apsk_4_5'] = isset($data['mc_32_apsk_4_5']) ? $data['mc_32_apsk_4_5'] : null;
        $this->container['mc_32_apsk_5_6'] = isset($data['mc_32_apsk_5_6']) ? $data['mc_32_apsk_5_6'] : null;
        $this->container['mc_32_apsk_8_9'] = isset($data['mc_32_apsk_8_9']) ? $data['mc_32_apsk_8_9'] : null;
        $this->container['mc_32_apsk_9_10'] = isset($data['mc_32_apsk_9_10']) ? $data['mc_32_apsk_9_10'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets mc_qpsk_1_4
     * @return double
     */
    public function getMcQpsk14()
    {
        return $this->container['mc_qpsk_1_4'];
    }

    /**
     * Sets mc_qpsk_1_4
     * @param double $mc_qpsk_1_4
     * @return $this
     */
    public function setMcQpsk14($mc_qpsk_1_4)
    {
        $this->container['mc_qpsk_1_4'] = $mc_qpsk_1_4;

        return $this;
    }

    /**
     * Gets mc_qpsk_1_3
     * @return double
     */
    public function getMcQpsk13()
    {
        return $this->container['mc_qpsk_1_3'];
    }

    /**
     * Sets mc_qpsk_1_3
     * @param double $mc_qpsk_1_3
     * @return $this
     */
    public function setMcQpsk13($mc_qpsk_1_3)
    {
        $this->container['mc_qpsk_1_3'] = $mc_qpsk_1_3;

        return $this;
    }

    /**
     * Gets mc_qpsk_2_5
     * @return double
     */
    public function getMcQpsk25()
    {
        return $this->container['mc_qpsk_2_5'];
    }

    /**
     * Sets mc_qpsk_2_5
     * @param double $mc_qpsk_2_5
     * @return $this
     */
    public function setMcQpsk25($mc_qpsk_2_5)
    {
        $this->container['mc_qpsk_2_5'] = $mc_qpsk_2_5;

        return $this;
    }

    /**
     * Gets mc_qpsk_1_2
     * @return double
     */
    public function getMcQpsk12()
    {
        return $this->container['mc_qpsk_1_2'];
    }

    /**
     * Sets mc_qpsk_1_2
     * @param double $mc_qpsk_1_2
     * @return $this
     */
    public function setMcQpsk12($mc_qpsk_1_2)
    {
        $this->container['mc_qpsk_1_2'] = $mc_qpsk_1_2;

        return $this;
    }

    /**
     * Gets mc_qpsk_3_5
     * @return double
     */
    public function getMcQpsk35()
    {
        return $this->container['mc_qpsk_3_5'];
    }

    /**
     * Sets mc_qpsk_3_5
     * @param double $mc_qpsk_3_5
     * @return $this
     */
    public function setMcQpsk35($mc_qpsk_3_5)
    {
        $this->container['mc_qpsk_3_5'] = $mc_qpsk_3_5;

        return $this;
    }

    /**
     * Gets mc_qpsk_2_3
     * @return double
     */
    public function getMcQpsk23()
    {
        return $this->container['mc_qpsk_2_3'];
    }

    /**
     * Sets mc_qpsk_2_3
     * @param double $mc_qpsk_2_3
     * @return $this
     */
    public function setMcQpsk23($mc_qpsk_2_3)
    {
        $this->container['mc_qpsk_2_3'] = $mc_qpsk_2_3;

        return $this;
    }

    /**
     * Gets mc_qpsk_3_4
     * @return double
     */
    public function getMcQpsk34()
    {
        return $this->container['mc_qpsk_3_4'];
    }

    /**
     * Sets mc_qpsk_3_4
     * @param double $mc_qpsk_3_4
     * @return $this
     */
    public function setMcQpsk34($mc_qpsk_3_4)
    {
        $this->container['mc_qpsk_3_4'] = $mc_qpsk_3_4;

        return $this;
    }

    /**
     * Gets mc_qpsk_4_5
     * @return double
     */
    public function getMcQpsk45()
    {
        return $this->container['mc_qpsk_4_5'];
    }

    /**
     * Sets mc_qpsk_4_5
     * @param double $mc_qpsk_4_5
     * @return $this
     */
    public function setMcQpsk45($mc_qpsk_4_5)
    {
        $this->container['mc_qpsk_4_5'] = $mc_qpsk_4_5;

        return $this;
    }

    /**
     * Gets mc_qpsk_5_6
     * @return double
     */
    public function getMcQpsk56()
    {
        return $this->container['mc_qpsk_5_6'];
    }

    /**
     * Sets mc_qpsk_5_6
     * @param double $mc_qpsk_5_6
     * @return $this
     */
    public function setMcQpsk56($mc_qpsk_5_6)
    {
        $this->container['mc_qpsk_5_6'] = $mc_qpsk_5_6;

        return $this;
    }

    /**
     * Gets mc_qpsk_8_9
     * @return double
     */
    public function getMcQpsk89()
    {
        return $this->container['mc_qpsk_8_9'];
    }

    /**
     * Sets mc_qpsk_8_9
     * @param double $mc_qpsk_8_9
     * @return $this
     */
    public function setMcQpsk89($mc_qpsk_8_9)
    {
        $this->container['mc_qpsk_8_9'] = $mc_qpsk_8_9;

        return $this;
    }

    /**
     * Gets mc_qpsk_9_10
     * @return double
     */
    public function getMcQpsk910()
    {
        return $this->container['mc_qpsk_9_10'];
    }

    /**
     * Sets mc_qpsk_9_10
     * @param double $mc_qpsk_9_10
     * @return $this
     */
    public function setMcQpsk910($mc_qpsk_9_10)
    {
        $this->container['mc_qpsk_9_10'] = $mc_qpsk_9_10;

        return $this;
    }

    /**
     * Gets mc_8_psk_3_5
     * @return double
     */
    public function getMc8Psk35()
    {
        return $this->container['mc_8_psk_3_5'];
    }

    /**
     * Sets mc_8_psk_3_5
     * @param double $mc_8_psk_3_5
     * @return $this
     */
    public function setMc8Psk35($mc_8_psk_3_5)
    {
        $this->container['mc_8_psk_3_5'] = $mc_8_psk_3_5;

        return $this;
    }

    /**
     * Gets mc_8_psk_2_3
     * @return double
     */
    public function getMc8Psk23()
    {
        return $this->container['mc_8_psk_2_3'];
    }

    /**
     * Sets mc_8_psk_2_3
     * @param double $mc_8_psk_2_3
     * @return $this
     */
    public function setMc8Psk23($mc_8_psk_2_3)
    {
        $this->container['mc_8_psk_2_3'] = $mc_8_psk_2_3;

        return $this;
    }

    /**
     * Gets mc_8_psk_3_4
     * @return double
     */
    public function getMc8Psk34()
    {
        return $this->container['mc_8_psk_3_4'];
    }

    /**
     * Sets mc_8_psk_3_4
     * @param double $mc_8_psk_3_4
     * @return $this
     */
    public function setMc8Psk34($mc_8_psk_3_4)
    {
        $this->container['mc_8_psk_3_4'] = $mc_8_psk_3_4;

        return $this;
    }

    /**
     * Gets mc_8_psk_5_6
     * @return double
     */
    public function getMc8Psk56()
    {
        return $this->container['mc_8_psk_5_6'];
    }

    /**
     * Sets mc_8_psk_5_6
     * @param double $mc_8_psk_5_6
     * @return $this
     */
    public function setMc8Psk56($mc_8_psk_5_6)
    {
        $this->container['mc_8_psk_5_6'] = $mc_8_psk_5_6;

        return $this;
    }

    /**
     * Gets mc_8_psk_8_9
     * @return double
     */
    public function getMc8Psk89()
    {
        return $this->container['mc_8_psk_8_9'];
    }

    /**
     * Sets mc_8_psk_8_9
     * @param double $mc_8_psk_8_9
     * @return $this
     */
    public function setMc8Psk89($mc_8_psk_8_9)
    {
        $this->container['mc_8_psk_8_9'] = $mc_8_psk_8_9;

        return $this;
    }

    /**
     * Gets mc_8_psk_9_10
     * @return double
     */
    public function getMc8Psk910()
    {
        return $this->container['mc_8_psk_9_10'];
    }

    /**
     * Sets mc_8_psk_9_10
     * @param double $mc_8_psk_9_10
     * @return $this
     */
    public function setMc8Psk910($mc_8_psk_9_10)
    {
        $this->container['mc_8_psk_9_10'] = $mc_8_psk_9_10;

        return $this;
    }

    /**
     * Gets mc_16_apsk_2_3
     * @return double
     */
    public function getMc16Apsk23()
    {
        return $this->container['mc_16_apsk_2_3'];
    }

    /**
     * Sets mc_16_apsk_2_3
     * @param double $mc_16_apsk_2_3
     * @return $this
     */
    public function setMc16Apsk23($mc_16_apsk_2_3)
    {
        $this->container['mc_16_apsk_2_3'] = $mc_16_apsk_2_3;

        return $this;
    }

    /**
     * Gets mc_16_apsk_3_4
     * @return double
     */
    public function getMc16Apsk34()
    {
        return $this->container['mc_16_apsk_3_4'];
    }

    /**
     * Sets mc_16_apsk_3_4
     * @param double $mc_16_apsk_3_4
     * @return $this
     */
    public function setMc16Apsk34($mc_16_apsk_3_4)
    {
        $this->container['mc_16_apsk_3_4'] = $mc_16_apsk_3_4;

        return $this;
    }

    /**
     * Gets mc_16_apsk_4_5
     * @return double
     */
    public function getMc16Apsk45()
    {
        return $this->container['mc_16_apsk_4_5'];
    }

    /**
     * Sets mc_16_apsk_4_5
     * @param double $mc_16_apsk_4_5
     * @return $this
     */
    public function setMc16Apsk45($mc_16_apsk_4_5)
    {
        $this->container['mc_16_apsk_4_5'] = $mc_16_apsk_4_5;

        return $this;
    }

    /**
     * Gets mc_16_apsk_5_6
     * @return double
     */
    public function getMc16Apsk56()
    {
        return $this->container['mc_16_apsk_5_6'];
    }

    /**
     * Sets mc_16_apsk_5_6
     * @param double $mc_16_apsk_5_6
     * @return $this
     */
    public function setMc16Apsk56($mc_16_apsk_5_6)
    {
        $this->container['mc_16_apsk_5_6'] = $mc_16_apsk_5_6;

        return $this;
    }

    /**
     * Gets mc_16_apsk_8_9
     * @return double
     */
    public function getMc16Apsk89()
    {
        return $this->container['mc_16_apsk_8_9'];
    }

    /**
     * Sets mc_16_apsk_8_9
     * @param double $mc_16_apsk_8_9
     * @return $this
     */
    public function setMc16Apsk89($mc_16_apsk_8_9)
    {
        $this->container['mc_16_apsk_8_9'] = $mc_16_apsk_8_9;

        return $this;
    }

    /**
     * Gets mc_16_apsk_9_10
     * @return double
     */
    public function getMc16Apsk910()
    {
        return $this->container['mc_16_apsk_9_10'];
    }

    /**
     * Sets mc_16_apsk_9_10
     * @param double $mc_16_apsk_9_10
     * @return $this
     */
    public function setMc16Apsk910($mc_16_apsk_9_10)
    {
        $this->container['mc_16_apsk_9_10'] = $mc_16_apsk_9_10;

        return $this;
    }

    /**
     * Gets mc_32_apsk_3_4
     * @return double
     */
    public function getMc32Apsk34()
    {
        return $this->container['mc_32_apsk_3_4'];
    }

    /**
     * Sets mc_32_apsk_3_4
     * @param double $mc_32_apsk_3_4
     * @return $this
     */
    public function setMc32Apsk34($mc_32_apsk_3_4)
    {
        $this->container['mc_32_apsk_3_4'] = $mc_32_apsk_3_4;

        return $this;
    }

    /**
     * Gets mc_32_apsk_4_5
     * @return double
     */
    public function getMc32Apsk45()
    {
        return $this->container['mc_32_apsk_4_5'];
    }

    /**
     * Sets mc_32_apsk_4_5
     * @param double $mc_32_apsk_4_5
     * @return $this
     */
    public function setMc32Apsk45($mc_32_apsk_4_5)
    {
        $this->container['mc_32_apsk_4_5'] = $mc_32_apsk_4_5;

        return $this;
    }

    /**
     * Gets mc_32_apsk_5_6
     * @return double
     */
    public function getMc32Apsk56()
    {
        return $this->container['mc_32_apsk_5_6'];
    }

    /**
     * Sets mc_32_apsk_5_6
     * @param double $mc_32_apsk_5_6
     * @return $this
     */
    public function setMc32Apsk56($mc_32_apsk_5_6)
    {
        $this->container['mc_32_apsk_5_6'] = $mc_32_apsk_5_6;

        return $this;
    }

    /**
     * Gets mc_32_apsk_8_9
     * @return double
     */
    public function getMc32Apsk89()
    {
        return $this->container['mc_32_apsk_8_9'];
    }

    /**
     * Sets mc_32_apsk_8_9
     * @param double $mc_32_apsk_8_9
     * @return $this
     */
    public function setMc32Apsk89($mc_32_apsk_8_9)
    {
        $this->container['mc_32_apsk_8_9'] = $mc_32_apsk_8_9;

        return $this;
    }

    /**
     * Gets mc_32_apsk_9_10
     * @return double
     */
    public function getMc32Apsk910()
    {
        return $this->container['mc_32_apsk_9_10'];
    }

    /**
     * Sets mc_32_apsk_9_10
     * @param double $mc_32_apsk_9_10
     * @return $this
     */
    public function setMc32Apsk910($mc_32_apsk_9_10)
    {
        $this->container['mc_32_apsk_9_10'] = $mc_32_apsk_9_10;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


