<?php
/**
 * ConfigTables
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iVantage API
 *
 * This is the iDirect iVantage API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * ConfigTables Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ConfigTables implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ConfigTables';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'config_table_number' => 'int',
        'import_map_number' => 'int',
        'export_map_number' => 'int',
        'advertise_map_number' => 'int',
        'non_exist_map_number' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'config_table_number' => 'int32',
        'import_map_number' => 'int32',
        'export_map_number' => 'int32',
        'advertise_map_number' => 'int32',
        'non_exist_map_number' => 'int32'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'config_table_number' => 'ConfigTableNumber',
        'import_map_number' => 'ImportMapNumber',
        'export_map_number' => 'ExportMapNumber',
        'advertise_map_number' => 'AdvertiseMapNumber',
        'non_exist_map_number' => 'NonExistMapNumber'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'config_table_number' => 'setConfigTableNumber',
        'import_map_number' => 'setImportMapNumber',
        'export_map_number' => 'setExportMapNumber',
        'advertise_map_number' => 'setAdvertiseMapNumber',
        'non_exist_map_number' => 'setNonExistMapNumber'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'config_table_number' => 'getConfigTableNumber',
        'import_map_number' => 'getImportMapNumber',
        'export_map_number' => 'getExportMapNumber',
        'advertise_map_number' => 'getAdvertiseMapNumber',
        'non_exist_map_number' => 'getNonExistMapNumber'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['config_table_number'] = isset($data['config_table_number']) ? $data['config_table_number'] : null;
        $this->container['import_map_number'] = isset($data['import_map_number']) ? $data['import_map_number'] : null;
        $this->container['export_map_number'] = isset($data['export_map_number']) ? $data['export_map_number'] : null;
        $this->container['advertise_map_number'] = isset($data['advertise_map_number']) ? $data['advertise_map_number'] : null;
        $this->container['non_exist_map_number'] = isset($data['non_exist_map_number']) ? $data['non_exist_map_number'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets config_table_number
     *
     * @return int
     */
    public function getConfigTableNumber()
    {
        return $this->container['config_table_number'];
    }

    /**
     * Sets config_table_number
     *
     * @param int $config_table_number config_table_number
     *
     * @return $this
     */
    public function setConfigTableNumber($config_table_number)
    {
        $this->container['config_table_number'] = $config_table_number;

        return $this;
    }

    /**
     * Gets import_map_number
     *
     * @return int
     */
    public function getImportMapNumber()
    {
        return $this->container['import_map_number'];
    }

    /**
     * Sets import_map_number
     *
     * @param int $import_map_number import_map_number
     *
     * @return $this
     */
    public function setImportMapNumber($import_map_number)
    {
        $this->container['import_map_number'] = $import_map_number;

        return $this;
    }

    /**
     * Gets export_map_number
     *
     * @return int
     */
    public function getExportMapNumber()
    {
        return $this->container['export_map_number'];
    }

    /**
     * Sets export_map_number
     *
     * @param int $export_map_number export_map_number
     *
     * @return $this
     */
    public function setExportMapNumber($export_map_number)
    {
        $this->container['export_map_number'] = $export_map_number;

        return $this;
    }

    /**
     * Gets advertise_map_number
     *
     * @return int
     */
    public function getAdvertiseMapNumber()
    {
        return $this->container['advertise_map_number'];
    }

    /**
     * Sets advertise_map_number
     *
     * @param int $advertise_map_number advertise_map_number
     *
     * @return $this
     */
    public function setAdvertiseMapNumber($advertise_map_number)
    {
        $this->container['advertise_map_number'] = $advertise_map_number;

        return $this;
    }

    /**
     * Gets non_exist_map_number
     *
     * @return int
     */
    public function getNonExistMapNumber()
    {
        return $this->container['non_exist_map_number'];
    }

    /**
     * Sets non_exist_map_number
     *
     * @param int $non_exist_map_number non_exist_map_number
     *
     * @return $this
     */
    public function setNonExistMapNumber($non_exist_map_number)
    {
        $this->container['non_exist_map_number'] = $non_exist_map_number;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


