<?php
/**
 * L3SVNUpstreamInterface
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iVantage API
 *
 * This is the iDirect iVantage API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * L3SVNUpstreamInterface Class Doc Comment
 *
 * @category    Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class L3SVNUpstreamInterface implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'L3SVN_UpstreamInterface';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'override_addresses' => 'bool',
        'enable_ri_pv2' => 'bool',
        'address_start' => 'string',
        'address_end' => 'string',
        'subnet_mask' => 'string',
        'gateway' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'override_addresses' => null,
        'enable_ri_pv2' => null,
        'address_start' => null,
        'address_end' => null,
        'subnet_mask' => null,
        'gateway' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'override_addresses' => 'OverrideAddresses',
        'enable_ri_pv2' => 'EnableRIPv2',
        'address_start' => 'AddressStart',
        'address_end' => 'AddressEnd',
        'subnet_mask' => 'SubnetMask',
        'gateway' => 'Gateway'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'override_addresses' => 'setOverrideAddresses',
        'enable_ri_pv2' => 'setEnableRiPv2',
        'address_start' => 'setAddressStart',
        'address_end' => 'setAddressEnd',
        'subnet_mask' => 'setSubnetMask',
        'gateway' => 'setGateway'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'override_addresses' => 'getOverrideAddresses',
        'enable_ri_pv2' => 'getEnableRiPv2',
        'address_start' => 'getAddressStart',
        'address_end' => 'getAddressEnd',
        'subnet_mask' => 'getSubnetMask',
        'gateway' => 'getGateway'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['override_addresses'] = isset($data['override_addresses']) ? $data['override_addresses'] : null;
        $this->container['enable_ri_pv2'] = isset($data['enable_ri_pv2']) ? $data['enable_ri_pv2'] : null;
        $this->container['address_start'] = isset($data['address_start']) ? $data['address_start'] : null;
        $this->container['address_end'] = isset($data['address_end']) ? $data['address_end'] : null;
        $this->container['subnet_mask'] = isset($data['subnet_mask']) ? $data['subnet_mask'] : null;
        $this->container['gateway'] = isset($data['gateway']) ? $data['gateway'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets override_addresses
     * @return bool
     */
    public function getOverrideAddresses()
    {
        return $this->container['override_addresses'];
    }

    /**
     * Sets override_addresses
     * @param bool $override_addresses
     * @return $this
     */
    public function setOverrideAddresses($override_addresses)
    {
        $this->container['override_addresses'] = $override_addresses;

        return $this;
    }

    /**
     * Gets enable_ri_pv2
     * @return bool
     */
    public function getEnableRiPv2()
    {
        return $this->container['enable_ri_pv2'];
    }

    /**
     * Sets enable_ri_pv2
     * @param bool $enable_ri_pv2
     * @return $this
     */
    public function setEnableRiPv2($enable_ri_pv2)
    {
        $this->container['enable_ri_pv2'] = $enable_ri_pv2;

        return $this;
    }

    /**
     * Gets address_start
     * @return string
     */
    public function getAddressStart()
    {
        return $this->container['address_start'];
    }

    /**
     * Sets address_start
     * @param string $address_start
     * @return $this
     */
    public function setAddressStart($address_start)
    {
        $this->container['address_start'] = $address_start;

        return $this;
    }

    /**
     * Gets address_end
     * @return string
     */
    public function getAddressEnd()
    {
        return $this->container['address_end'];
    }

    /**
     * Sets address_end
     * @param string $address_end
     * @return $this
     */
    public function setAddressEnd($address_end)
    {
        $this->container['address_end'] = $address_end;

        return $this;
    }

    /**
     * Gets subnet_mask
     * @return string
     */
    public function getSubnetMask()
    {
        return $this->container['subnet_mask'];
    }

    /**
     * Sets subnet_mask
     * @param string $subnet_mask
     * @return $this
     */
    public function setSubnetMask($subnet_mask)
    {
        $this->container['subnet_mask'] = $subnet_mask;

        return $this;
    }

    /**
     * Gets gateway
     * @return string
     */
    public function getGateway()
    {
        return $this->container['gateway'];
    }

    /**
     * Sets gateway
     * @param string $gateway
     * @return $this
     */
    public function setGateway($gateway)
    {
        $this->container['gateway'] = $gateway;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


