<?php
/**
 * RemoteRemoteQOSUSAdaptive
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iVantage API
 *
 * This is the iDirect iVantage API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * RemoteRemoteQOSUSAdaptive Class Doc Comment
 *
 * @category    Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RemoteRemoteQOSUSAdaptive implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'Remote_RemoteQOS_USAdaptive';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'enable_max_impairment' => 'bool',
        'max_impairment' => 'double',
        'max_symrate' => 'double',
        'max_cn' => 'double'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'enable_max_impairment' => null,
        'max_impairment' => 'double',
        'max_symrate' => 'double',
        'max_cn' => 'double'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'enable_max_impairment' => 'EnableMaxImpairment',
        'max_impairment' => 'MaxImpairment',
        'max_symrate' => 'MaxSymrate',
        'max_cn' => 'MaxCN'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'enable_max_impairment' => 'setEnableMaxImpairment',
        'max_impairment' => 'setMaxImpairment',
        'max_symrate' => 'setMaxSymrate',
        'max_cn' => 'setMaxCn'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'enable_max_impairment' => 'getEnableMaxImpairment',
        'max_impairment' => 'getMaxImpairment',
        'max_symrate' => 'getMaxSymrate',
        'max_cn' => 'getMaxCn'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['enable_max_impairment'] = isset($data['enable_max_impairment']) ? $data['enable_max_impairment'] : null;
        $this->container['max_impairment'] = isset($data['max_impairment']) ? $data['max_impairment'] : null;
        $this->container['max_symrate'] = isset($data['max_symrate']) ? $data['max_symrate'] : null;
        $this->container['max_cn'] = isset($data['max_cn']) ? $data['max_cn'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets enable_max_impairment
     * @return bool
     */
    public function getEnableMaxImpairment()
    {
        return $this->container['enable_max_impairment'];
    }

    /**
     * Sets enable_max_impairment
     * @param bool $enable_max_impairment
     * @return $this
     */
    public function setEnableMaxImpairment($enable_max_impairment)
    {
        $this->container['enable_max_impairment'] = $enable_max_impairment;

        return $this;
    }

    /**
     * Gets max_impairment
     * @return double
     */
    public function getMaxImpairment()
    {
        return $this->container['max_impairment'];
    }

    /**
     * Sets max_impairment
     * @param double $max_impairment
     * @return $this
     */
    public function setMaxImpairment($max_impairment)
    {
        $this->container['max_impairment'] = $max_impairment;

        return $this;
    }

    /**
     * Gets max_symrate
     * @return double
     */
    public function getMaxSymrate()
    {
        return $this->container['max_symrate'];
    }

    /**
     * Sets max_symrate
     * @param double $max_symrate
     * @return $this
     */
    public function setMaxSymrate($max_symrate)
    {
        $this->container['max_symrate'] = $max_symrate;

        return $this;
    }

    /**
     * Gets max_cn
     * @return double
     */
    public function getMaxCn()
    {
        return $this->container['max_cn'];
    }

    /**
     * Sets max_cn
     * @param double $max_cn
     * @return $this
     */
    public function setMaxCn($max_cn)
    {
        $this->container['max_cn'] = $max_cn;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


