<?php
/**
 * RemoteSecondReceiverSecondRxPort
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iVantage API
 *
 * This is the iDirect iVantage API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * RemoteSecondReceiverSecondRxPort Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RemoteSecondReceiverSecondRxPort implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Remote_SecondReceiver_SecondRxPort';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'ifl' => 'string',
        'lnbid' => 'int',
        'boost_lnb_voltage' => 'bool',
        'mcfp_encryption' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'ifl' => null,
        'lnbid' => 'int32',
        'boost_lnb_voltage' => null,
        'mcfp_encryption' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ifl' => 'IFL',
        'lnbid' => 'LNBID',
        'boost_lnb_voltage' => 'BoostLnbVoltage',
        'mcfp_encryption' => 'MCFPEncryption'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ifl' => 'setIfl',
        'lnbid' => 'setLnbid',
        'boost_lnb_voltage' => 'setBoostLnbVoltage',
        'mcfp_encryption' => 'setMcfpEncryption'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ifl' => 'getIfl',
        'lnbid' => 'getLnbid',
        'boost_lnb_voltage' => 'getBoostLnbVoltage',
        'mcfp_encryption' => 'getMcfpEncryption'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['ifl'] = isset($data['ifl']) ? $data['ifl'] : null;
        $this->container['lnbid'] = isset($data['lnbid']) ? $data['lnbid'] : null;
        $this->container['boost_lnb_voltage'] = isset($data['boost_lnb_voltage']) ? $data['boost_lnb_voltage'] : null;
        $this->container['mcfp_encryption'] = isset($data['mcfp_encryption']) ? $data['mcfp_encryption'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets ifl
     *
     * @return string
     */
    public function getIfl()
    {
        return $this->container['ifl'];
    }

    /**
     * Sets ifl
     *
     * @param string $ifl ifl
     *
     * @return $this
     */
    public function setIfl($ifl)
    {
        $this->container['ifl'] = $ifl;

        return $this;
    }

    /**
     * Gets lnbid
     *
     * @return int
     */
    public function getLnbid()
    {
        return $this->container['lnbid'];
    }

    /**
     * Sets lnbid
     *
     * @param int $lnbid lnbid
     *
     * @return $this
     */
    public function setLnbid($lnbid)
    {
        $this->container['lnbid'] = $lnbid;

        return $this;
    }

    /**
     * Gets boost_lnb_voltage
     *
     * @return bool
     */
    public function getBoostLnbVoltage()
    {
        return $this->container['boost_lnb_voltage'];
    }

    /**
     * Sets boost_lnb_voltage
     *
     * @param bool $boost_lnb_voltage boost_lnb_voltage
     *
     * @return $this
     */
    public function setBoostLnbVoltage($boost_lnb_voltage)
    {
        $this->container['boost_lnb_voltage'] = $boost_lnb_voltage;

        return $this;
    }

    /**
     * Gets mcfp_encryption
     *
     * @return bool
     */
    public function getMcfpEncryption()
    {
        return $this->container['mcfp_encryption'];
    }

    /**
     * Sets mcfp_encryption
     *
     * @param bool $mcfp_encryption mcfp_encryption
     *
     * @return $this
     */
    public function setMcfpEncryption($mcfp_encryption)
    {
        $this->container['mcfp_encryption'] = $mcfp_encryption;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


