<?php
/**
 * RemoteL2oS
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iVantage API
 *
 * This is the iDirect iVantage API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * RemoteL2oS Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RemoteL2oS implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Remote_L2oS';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'sdt' => 'int',
        'compression' => 'int',
        'mtu' => 'int',
        'ethertype1' => 'string',
        'ethertype2' => 'string',
        'bfd' => 'bool',
        'header_compression' => '\Swagger\Client\Model\RemoteL2oSHeaderCompression',
        'svns' => '\Swagger\Client\Model\SVN[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'sdt' => 'int32',
        'compression' => 'int32',
        'mtu' => 'int32',
        'ethertype1' => null,
        'ethertype2' => null,
        'bfd' => null,
        'header_compression' => null,
        'svns' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'sdt' => 'SDT',
        'compression' => 'Compression',
        'mtu' => 'MTU',
        'ethertype1' => 'Ethertype1',
        'ethertype2' => 'Ethertype2',
        'bfd' => 'BFD',
        'header_compression' => 'HeaderCompression',
        'svns' => 'SVNs'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'sdt' => 'setSdt',
        'compression' => 'setCompression',
        'mtu' => 'setMtu',
        'ethertype1' => 'setEthertype1',
        'ethertype2' => 'setEthertype2',
        'bfd' => 'setBfd',
        'header_compression' => 'setHeaderCompression',
        'svns' => 'setSvns'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'sdt' => 'getSdt',
        'compression' => 'getCompression',
        'mtu' => 'getMtu',
        'ethertype1' => 'getEthertype1',
        'ethertype2' => 'getEthertype2',
        'bfd' => 'getBfd',
        'header_compression' => 'getHeaderCompression',
        'svns' => 'getSvns'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['sdt'] = isset($data['sdt']) ? $data['sdt'] : null;
        $this->container['compression'] = isset($data['compression']) ? $data['compression'] : null;
        $this->container['mtu'] = isset($data['mtu']) ? $data['mtu'] : null;
        $this->container['ethertype1'] = isset($data['ethertype1']) ? $data['ethertype1'] : null;
        $this->container['ethertype2'] = isset($data['ethertype2']) ? $data['ethertype2'] : null;
        $this->container['bfd'] = isset($data['bfd']) ? $data['bfd'] : null;
        $this->container['header_compression'] = isset($data['header_compression']) ? $data['header_compression'] : null;
        $this->container['svns'] = isset($data['svns']) ? $data['svns'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets sdt
     *
     * @return int
     */
    public function getSdt()
    {
        return $this->container['sdt'];
    }

    /**
     * Sets sdt
     *
     * @param int $sdt sdt
     *
     * @return $this
     */
    public function setSdt($sdt)
    {
        $this->container['sdt'] = $sdt;

        return $this;
    }

    /**
     * Gets compression
     *
     * @return int
     */
    public function getCompression()
    {
        return $this->container['compression'];
    }

    /**
     * Sets compression
     *
     * @param int $compression compression
     *
     * @return $this
     */
    public function setCompression($compression)
    {
        $this->container['compression'] = $compression;

        return $this;
    }

    /**
     * Gets mtu
     *
     * @return int
     */
    public function getMtu()
    {
        return $this->container['mtu'];
    }

    /**
     * Sets mtu
     *
     * @param int $mtu mtu
     *
     * @return $this
     */
    public function setMtu($mtu)
    {
        $this->container['mtu'] = $mtu;

        return $this;
    }

    /**
     * Gets ethertype1
     *
     * @return string
     */
    public function getEthertype1()
    {
        return $this->container['ethertype1'];
    }

    /**
     * Sets ethertype1
     *
     * @param string $ethertype1 ethertype1
     *
     * @return $this
     */
    public function setEthertype1($ethertype1)
    {
        $this->container['ethertype1'] = $ethertype1;

        return $this;
    }

    /**
     * Gets ethertype2
     *
     * @return string
     */
    public function getEthertype2()
    {
        return $this->container['ethertype2'];
    }

    /**
     * Sets ethertype2
     *
     * @param string $ethertype2 ethertype2
     *
     * @return $this
     */
    public function setEthertype2($ethertype2)
    {
        $this->container['ethertype2'] = $ethertype2;

        return $this;
    }

    /**
     * Gets bfd
     *
     * @return bool
     */
    public function getBfd()
    {
        return $this->container['bfd'];
    }

    /**
     * Sets bfd
     *
     * @param bool $bfd bfd
     *
     * @return $this
     */
    public function setBfd($bfd)
    {
        $this->container['bfd'] = $bfd;

        return $this;
    }

    /**
     * Gets header_compression
     *
     * @return \Swagger\Client\Model\RemoteL2oSHeaderCompression
     */
    public function getHeaderCompression()
    {
        return $this->container['header_compression'];
    }

    /**
     * Sets header_compression
     *
     * @param \Swagger\Client\Model\RemoteL2oSHeaderCompression $header_compression header_compression
     *
     * @return $this
     */
    public function setHeaderCompression($header_compression)
    {
        $this->container['header_compression'] = $header_compression;

        return $this;
    }

    /**
     * Gets svns
     *
     * @return \Swagger\Client\Model\SVN[]
     */
    public function getSvns()
    {
        return $this->container['svns'];
    }

    /**
     * Sets svns
     *
     * @param \Swagger\Client\Model\SVN[] $svns svns
     *
     * @return $this
     */
    public function setSvns($svns)
    {
        $this->container['svns'] = $svns;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


