<?php
/**
 * RoamingInstance
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iVantage API
 *
 * This is the iDirect iVantage API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * RoamingInstance Class Doc Comment
 *
 * @category    Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RoamingInstance implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'RoamingInstance';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'int',
        'network_id' => 'int',
        'inroute_group_id' => 'int',
        'scpc_peer_id' => 'int',
        'is_scpc' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => 'int32',
        'network_id' => 'int32',
        'inroute_group_id' => 'int32',
        'scpc_peer_id' => 'int32',
        'is_scpc' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'ID',
        'network_id' => 'NetworkID',
        'inroute_group_id' => 'InrouteGroupID',
        'scpc_peer_id' => 'SCPCPeerID',
        'is_scpc' => 'IsSCPC'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'network_id' => 'setNetworkId',
        'inroute_group_id' => 'setInrouteGroupId',
        'scpc_peer_id' => 'setScpcPeerId',
        'is_scpc' => 'setIsScpc'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'network_id' => 'getNetworkId',
        'inroute_group_id' => 'getInrouteGroupId',
        'scpc_peer_id' => 'getScpcPeerId',
        'is_scpc' => 'getIsScpc'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['network_id'] = isset($data['network_id']) ? $data['network_id'] : null;
        $this->container['inroute_group_id'] = isset($data['inroute_group_id']) ? $data['inroute_group_id'] : null;
        $this->container['scpc_peer_id'] = isset($data['scpc_peer_id']) ? $data['scpc_peer_id'] : null;
        $this->container['is_scpc'] = isset($data['is_scpc']) ? $data['is_scpc'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets id
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     * @param int $id
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets network_id
     * @return int
     */
    public function getNetworkId()
    {
        return $this->container['network_id'];
    }

    /**
     * Sets network_id
     * @param int $network_id
     * @return $this
     */
    public function setNetworkId($network_id)
    {
        $this->container['network_id'] = $network_id;

        return $this;
    }

    /**
     * Gets inroute_group_id
     * @return int
     */
    public function getInrouteGroupId()
    {
        return $this->container['inroute_group_id'];
    }

    /**
     * Sets inroute_group_id
     * @param int $inroute_group_id
     * @return $this
     */
    public function setInrouteGroupId($inroute_group_id)
    {
        $this->container['inroute_group_id'] = $inroute_group_id;

        return $this;
    }

    /**
     * Gets scpc_peer_id
     * @return int
     */
    public function getScpcPeerId()
    {
        return $this->container['scpc_peer_id'];
    }

    /**
     * Sets scpc_peer_id
     * @param int $scpc_peer_id
     * @return $this
     */
    public function setScpcPeerId($scpc_peer_id)
    {
        $this->container['scpc_peer_id'] = $scpc_peer_id;

        return $this;
    }

    /**
     * Gets is_scpc
     * @return bool
     */
    public function getIsScpc()
    {
        return $this->container['is_scpc'];
    }

    /**
     * Sets is_scpc
     * @param bool $is_scpc
     * @return $this
     */
    public function setIsScpc($is_scpc)
    {
        $this->container['is_scpc'] = $is_scpc;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


