<?php
/**
 * SVNL3BGPRouteRedistribution
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iVantage API
 *
 * This is the iDirect iVantage API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * SVNL3BGPRouteRedistribution Class Doc Comment
 *
 * @category    Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SVNL3BGPRouteRedistribution implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'SVN_L3_BGP_RouteRedistribution';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'static_routes_enabled' => 'bool',
        'connected_routes_enabled' => 'bool',
        'rip_routes_enabled' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'static_routes_enabled' => null,
        'connected_routes_enabled' => null,
        'rip_routes_enabled' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'static_routes_enabled' => 'StaticRoutesEnabled',
        'connected_routes_enabled' => 'ConnectedRoutesEnabled',
        'rip_routes_enabled' => 'RIPRoutesEnabled'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'static_routes_enabled' => 'setStaticRoutesEnabled',
        'connected_routes_enabled' => 'setConnectedRoutesEnabled',
        'rip_routes_enabled' => 'setRipRoutesEnabled'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'static_routes_enabled' => 'getStaticRoutesEnabled',
        'connected_routes_enabled' => 'getConnectedRoutesEnabled',
        'rip_routes_enabled' => 'getRipRoutesEnabled'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['static_routes_enabled'] = isset($data['static_routes_enabled']) ? $data['static_routes_enabled'] : null;
        $this->container['connected_routes_enabled'] = isset($data['connected_routes_enabled']) ? $data['connected_routes_enabled'] : null;
        $this->container['rip_routes_enabled'] = isset($data['rip_routes_enabled']) ? $data['rip_routes_enabled'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets static_routes_enabled
     * @return bool
     */
    public function getStaticRoutesEnabled()
    {
        return $this->container['static_routes_enabled'];
    }

    /**
     * Sets static_routes_enabled
     * @param bool $static_routes_enabled
     * @return $this
     */
    public function setStaticRoutesEnabled($static_routes_enabled)
    {
        $this->container['static_routes_enabled'] = $static_routes_enabled;

        return $this;
    }

    /**
     * Gets connected_routes_enabled
     * @return bool
     */
    public function getConnectedRoutesEnabled()
    {
        return $this->container['connected_routes_enabled'];
    }

    /**
     * Sets connected_routes_enabled
     * @param bool $connected_routes_enabled
     * @return $this
     */
    public function setConnectedRoutesEnabled($connected_routes_enabled)
    {
        $this->container['connected_routes_enabled'] = $connected_routes_enabled;

        return $this;
    }

    /**
     * Gets rip_routes_enabled
     * @return bool
     */
    public function getRipRoutesEnabled()
    {
        return $this->container['rip_routes_enabled'];
    }

    /**
     * Sets rip_routes_enabled
     * @param bool $rip_routes_enabled
     * @return $this
     */
    public function setRipRoutesEnabled($rip_routes_enabled)
    {
        $this->container['rip_routes_enabled'] = $rip_routes_enabled;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


