<?php
/**
 * AggregateAddressTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iVantage API
 *
 * This is the iDirect iVantage API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AggregateAddressTest Class Doc Comment
 *
 * @category    Class
 * @description AggregateAddress
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AggregateAddressTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AggregateAddress"
     */
    public function testAggregateAddress()
    {
    }

    /**
     * Test attribute "aggregate_address_number"
     */
    public function testPropertyAggregateAddressNumber()
    {
    }

    /**
     * Test attribute "prefix_len"
     */
    public function testPropertyPrefixLen()
    {
    }

    /**
     * Test attribute "suppress_map_number"
     */
    public function testPropertySuppressMapNumber()
    {
    }

    /**
     * Test attribute "advertise_map_number"
     */
    public function testPropertyAdvertiseMapNumber()
    {
    }

    /**
     * Test attribute "attribute_map_number"
     */
    public function testPropertyAttributeMapNumber()
    {
    }

    /**
     * Test attribute "afi"
     */
    public function testPropertyAfi()
    {
    }

    /**
     * Test attribute "safi"
     */
    public function testPropertySafi()
    {
    }

    /**
     * Test attribute "prefix_addr"
     */
    public function testPropertyPrefixAddr()
    {
    }

    /**
     * Test attribute "option"
     */
    public function testPropertyOption()
    {
    }
}
