<?php
/**
 * ApplicationServiceGroupEffectiveRatesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iVantage API
 *
 * This is the iDirect iVantage API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ApplicationServiceGroupEffectiveRatesTest Class Doc Comment
 *
 * @category    Class */
// * @description ApplicationServiceGroupEffectiveRates
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ApplicationServiceGroupEffectiveRatesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ApplicationServiceGroupEffectiveRates"
     */
    public function testApplicationServiceGroupEffectiveRates()
    {
    }

    /**
     * Test attribute "cost"
     */
    public function testPropertyCost()
    {
    }

    /**
     * Test attribute "mi_rkbps"
     */
    public function testPropertyMiRkbps()
    {
    }

    /**
     * Test attribute "ci_rkbps"
     */
    public function testPropertyCiRkbps()
    {
    }

    /**
     * Test attribute "mir_modcod_table"
     */
    public function testPropertyMirModcodTable()
    {
    }

    /**
     * Test attribute "cir_modcod_table"
     */
    public function testPropertyCirModcodTable()
    {
    }
}
