<?php
/**
 * BladeDefaultVlanTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iVantage API
 *
 * This is the iDirect iVantage API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BladeDefaultVlanTest Class Doc Comment
 *
 * @category    Class */
// * @description BladeDefaultVlan
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BladeDefaultVlanTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BladeDefaultVlan"
     */
    public function testBladeDefaultVlan()
    {
    }

    /**
     * Test attribute "upstream_address"
     */
    public function testPropertyUpstreamAddress()
    {
    }

    /**
     * Test attribute "upstream_subnet_mask"
     */
    public function testPropertyUpstreamSubnetMask()
    {
    }

    /**
     * Test attribute "upstream_gateway"
     */
    public function testPropertyUpstreamGateway()
    {
    }

    /**
     * Test attribute "tunnel_address"
     */
    public function testPropertyTunnelAddress()
    {
    }

    /**
     * Test attribute "tunnel_subnet_mask"
     */
    public function testPropertyTunnelSubnetMask()
    {
    }
}
