<?php
/**
 * BUCTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iVantage API
 *
 * This is the iDirect iVantage API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BUCTest Class Doc Comment
 *
 * @category    Class
 * @description BUC
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BUCTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BUC"
     */
    public function testBUC()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "parent_id"
     */
    public function testPropertyParentId()
    {
    }

    /**
     * Test attribute "manufacturer"
     */
    public function testPropertyManufacturer()
    {
    }

    /**
     * Test attribute "i_direct_part_number"
     */
    public function testPropertyIDirectPartNumber()
    {
    }

    /**
     * Test attribute "tx_ref_oscillator"
     */
    public function testPropertyTxRefOscillator()
    {
    }

    /**
     * Test attribute "spectral_inversion"
     */
    public function testPropertySpectralInversion()
    {
    }

    /**
     * Test attribute "start_freq"
     */
    public function testPropertyStartFreq()
    {
    }

    /**
     * Test attribute "stop_freq"
     */
    public function testPropertyStopFreq()
    {
    }

    /**
     * Test attribute "gain"
     */
    public function testPropertyGain()
    {
    }

    /**
     * Test attribute "power"
     */
    public function testPropertyPower()
    {
    }

    /**
     * Test attribute "translation_freq"
     */
    public function testPropertyTranslationFreq()
    {
    }

    /**
     * Test attribute "tx_dc_enable"
     */
    public function testPropertyTxDcEnable()
    {
    }
}
