<?php
/**
 * L3SVNUpstreamInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iVantage API
 *
 * This is the iDirect iVantage API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * L3SVNUpstreamInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description L3SVNUpstreamInterface
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class L3SVNUpstreamInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "L3SVNUpstreamInterface"
     */
    public function testL3SVNUpstreamInterface()
    {
    }

    /**
     * Test attribute "override_addresses"
     */
    public function testPropertyOverrideAddresses()
    {
    }

    /**
     * Test attribute "enable_ri_pv2"
     */
    public function testPropertyEnableRiPv2()
    {
    }

    /**
     * Test attribute "address_start"
     */
    public function testPropertyAddressStart()
    {
    }

    /**
     * Test attribute "address_end"
     */
    public function testPropertyAddressEnd()
    {
    }

    /**
     * Test attribute "subnet_mask"
     */
    public function testPropertySubnetMask()
    {
    }

    /**
     * Test attribute "gateway"
     */
    public function testPropertyGateway()
    {
    }
}
