<?php
/**
 * LNBTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iVantage API
 *
 * This is the iDirect iVantage API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * LNBTest Class Doc Comment
 *
 * @category    Class */
// * @description LNB
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LNBTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LNB"
     */
    public function testLNB()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "parent_id"
     */
    public function testPropertyParentId()
    {
    }

    /**
     * Test attribute "manufacturer"
     */
    public function testPropertyManufacturer()
    {
    }

    /**
     * Test attribute "i_direct_part_number"
     */
    public function testPropertyIDirectPartNumber()
    {
    }

    /**
     * Test attribute "rx_dc_voltage"
     */
    public function testPropertyRxDcVoltage()
    {
    }

    /**
     * Test attribute "spectral_inversion"
     */
    public function testPropertySpectralInversion()
    {
    }

    /**
     * Test attribute "start_freq"
     */
    public function testPropertyStartFreq()
    {
    }

    /**
     * Test attribute "stop_freq"
     */
    public function testPropertyStopFreq()
    {
    }

    /**
     * Test attribute "gain"
     */
    public function testPropertyGain()
    {
    }

    /**
     * Test attribute "noise_figure"
     */
    public function testPropertyNoiseFigure()
    {
    }

    /**
     * Test attribute "translation_freq"
     */
    public function testPropertyTranslationFreq()
    {
    }

    /**
     * Test attribute "rx_dc_enable"
     */
    public function testPropertyRxDcEnable()
    {
    }

    /**
     * Test attribute "rx10_m_hz_enable"
     */
    public function testPropertyRx10MHzEnable()
    {
    }

    /**
     * Test attribute "_22_khz_enable"
     */
    public function testProperty22KhzEnable()
    {
    }
}
