<?php
/**
 * ProtocolProcessorL2oSTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iVantage API
 *
 * This is the iDirect iVantage API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ProtocolProcessorL2oSTest Class Doc Comment
 *
 * @category    Class */
// * @description ProtocolProcessorL2oS
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProtocolProcessorL2oSTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProtocolProcessorL2oS"
     */
    public function testProtocolProcessorL2oS()
    {
    }

    /**
     * Test attribute "enable_l2o_s"
     */
    public function testPropertyEnableL2oS()
    {
    }

    /**
     * Test attribute "reserve_outer_svn_for_l3"
     */
    public function testPropertyReserveOuterSvnForL3()
    {
    }

    /**
     * Test attribute "sdt_mode"
     */
    public function testPropertySdtMode()
    {
    }

    /**
     * Test attribute "ethertype1"
     */
    public function testPropertyEthertype1()
    {
    }

    /**
     * Test attribute "ethertype2"
     */
    public function testPropertyEthertype2()
    {
    }

    /**
     * Test attribute "l2_sw_mode"
     */
    public function testPropertyL2SwMode()
    {
    }

    /**
     * Test attribute "mac_rewrite"
     */
    public function testPropertyMacRewrite()
    {
    }

    /**
     * Test attribute "reserved_outer_svn_id"
     */
    public function testPropertyReservedOuterSvnId()
    {
    }
}
