<?php
/**
 * RemoteL2oSTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iVantage API
 *
 * This is the iDirect iVantage API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RemoteL2oSTest Class Doc Comment
 *
 * @category    Class */
// * @description RemoteL2oS
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RemoteL2oSTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RemoteL2oS"
     */
    public function testRemoteL2oS()
    {
    }

    /**
     * Test attribute "sdt"
     */
    public function testPropertySdt()
    {
    }

    /**
     * Test attribute "compression"
     */
    public function testPropertyCompression()
    {
    }

    /**
     * Test attribute "mtu"
     */
    public function testPropertyMtu()
    {
    }

    /**
     * Test attribute "ethertype1"
     */
    public function testPropertyEthertype1()
    {
    }

    /**
     * Test attribute "ethertype2"
     */
    public function testPropertyEthertype2()
    {
    }

    /**
     * Test attribute "bfd"
     */
    public function testPropertyBfd()
    {
    }

    /**
     * Test attribute "sv_ns"
     */
    public function testPropertySvNs()
    {
    }
}
