<?php
/**
 * RemoteRemoteQOSUSAdaptiveTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iVantage API
 *
 * This is the iDirect iVantage API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RemoteRemoteQOSUSAdaptiveTest Class Doc Comment
 *
 * @category    Class */
// * @description RemoteRemoteQOSUSAdaptive
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RemoteRemoteQOSUSAdaptiveTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RemoteRemoteQOSUSAdaptive"
     */
    public function testRemoteRemoteQOSUSAdaptive()
    {
    }

    /**
     * Test attribute "enable_max_impairment"
     */
    public function testPropertyEnableMaxImpairment()
    {
    }

    /**
     * Test attribute "max_impairment"
     */
    public function testPropertyMaxImpairment()
    {
    }

    /**
     * Test attribute "max_symrate"
     */
    public function testPropertyMaxSymrate()
    {
    }

    /**
     * Test attribute "max_cn"
     */
    public function testPropertyMaxCn()
    {
    }
}
