<?php
/**
 * RemoteMeshTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iVantage API
 *
 * This is the iDirect iVantage API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RemoteMeshTest Class Doc Comment
 *
 * @category    Class
 * @description RemoteMesh
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RemoteMeshTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RemoteMesh"
     */
    public function testRemoteMesh()
    {
    }

    /**
     * Test attribute "mode"
     */
    public function testPropertyMode()
    {
    }

    /**
     * Test attribute "receiver_ip_address"
     */
    public function testPropertyReceiverIpAddress()
    {
    }

    /**
     * Test attribute "receiver_subnet_mask"
     */
    public function testPropertyReceiverSubnetMask()
    {
    }

    /**
     * Test attribute "receiver_sn"
     */
    public function testPropertyReceiverSn()
    {
    }

    /**
     * Test attribute "receiver_fade_margin"
     */
    public function testPropertyReceiverFadeMargin()
    {
    }

    /**
     * Test attribute "receiver_hysteresis_margin"
     */
    public function testPropertyReceiverHysteresisMargin()
    {
    }
}
