<?php
/**
 * RuleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iVantage API
 *
 * This is the iDirect iVantage API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RuleTest Class Doc Comment
 *
 * @category    Class
 * @description Rule
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RuleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Rule"
     */
    public function testRule()
    {
    }

    /**
     * Test attribute "rule_number"
     */
    public function testPropertyRuleNumber()
    {
    }

    /**
     * Test attribute "continue"
     */
    public function testPropertyContinue()
    {
    }

    /**
     * Test attribute "ma_med"
     */
    public function testPropertyMaMed()
    {
    }

    /**
     * Test attribute "se_med"
     */
    public function testPropertySeMed()
    {
    }

    /**
     * Test attribute "se_as_times"
     */
    public function testPropertySeAsTimes()
    {
    }

    /**
     * Test attribute "se_local_pref"
     */
    public function testPropertySeLocalPref()
    {
    }

    /**
     * Test attribute "se_weight"
     */
    public function testPropertySeWeight()
    {
    }

    /**
     * Test attribute "snr_metric_route_map_index"
     */
    public function testPropertySnrMetricRouteMapIndex()
    {
    }

    /**
     * Test attribute "permit"
     */
    public function testPropertyPermit()
    {
    }

    /**
     * Test attribute "orf_association"
     */
    public function testPropertyOrfAssociation()
    {
    }

    /**
     * Test attribute "ma_afi"
     */
    public function testPropertyMaAfi()
    {
    }

    /**
     * Test attribute "ma_safi"
     */
    public function testPropertyMaSafi()
    {
    }

    /**
     * Test attribute "ma_as_path"
     */
    public function testPropertyMaAsPath()
    {
    }

    /**
     * Test attribute "ma_community"
     */
    public function testPropertyMaCommunity()
    {
    }

    /**
     * Test attribute "ma_ex_community"
     */
    public function testPropertyMaExCommunity()
    {
    }

    /**
     * Test attribute "se_community_action"
     */
    public function testPropertySeCommunityAction()
    {
    }

    /**
     * Test attribute "se_community"
     */
    public function testPropertySeCommunity()
    {
    }

    /**
     * Test attribute "se_ex_community_action"
     */
    public function testPropertySeExCommunityAction()
    {
    }

    /**
     * Test attribute "se_ex_community"
     */
    public function testPropertySeExCommunity()
    {
    }

    /**
     * Test attribute "se_as_action"
     */
    public function testPropertySeAsAction()
    {
    }

    /**
     * Test attribute "se_origin"
     */
    public function testPropertySeOrigin()
    {
    }

    /**
     * Test attribute "se_next_hop_address"
     */
    public function testPropertySeNextHopAddress()
    {
    }

    /**
     * Test attribute "ip_prefix"
     */
    public function testPropertyIpPrefix()
    {
    }
}
