<?php
/**
 * RuleIPPrefixTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iVantage API
 *
 * This is the iDirect iVantage API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RuleIPPrefixTest Class Doc Comment
 *
 * @category    Class */
// * @description RuleIPPrefix
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RuleIPPrefixTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RuleIPPrefix"
     */
    public function testRuleIPPrefix()
    {
    }

    /**
     * Test attribute "prefix_number"
     */
    public function testPropertyPrefixNumber()
    {
    }

    /**
     * Test attribute "len"
     */
    public function testPropertyLen()
    {
    }

    /**
     * Test attribute "le_value"
     */
    public function testPropertyLeValue()
    {
    }

    /**
     * Test attribute "ge_value"
     */
    public function testPropertyGeValue()
    {
    }

    /**
     * Test attribute "afi"
     */
    public function testPropertyAfi()
    {
    }

    /**
     * Test attribute "safi"
     */
    public function testPropertySafi()
    {
    }

    /**
     * Test attribute "match"
     */
    public function testPropertyMatch()
    {
    }

    /**
     * Test attribute "permit"
     */
    public function testPropertyPermit()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }
}
