<?php
/**
 * SpacecraftTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iVantage API
 *
 * This is the iDirect iVantage API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SpacecraftTest Class Doc Comment
 *
 * @category    Class
 * @description Spacecraft
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SpacecraftTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Spacecraft"
     */
    public function testSpacecraft()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "operator_id"
     */
    public function testPropertyOperatorId()
    {
    }

    /**
     * Test attribute "operator_ref_name"
     */
    public function testPropertyOperatorRefName()
    {
    }

    /**
     * Test attribute "longitude"
     */
    public function testPropertyLongitude()
    {
    }

    /**
     * Test attribute "incline_orbit"
     */
    public function testPropertyInclineOrbit()
    {
    }

    /**
     * Test attribute "minimum_look_angle"
     */
    public function testPropertyMinimumLookAngle()
    {
    }

    /**
     * Test attribute "max_skew"
     */
    public function testPropertyMaxSkew()
    {
    }

    /**
     * Test attribute "skew_polarization"
     */
    public function testPropertySkewPolarization()
    {
    }

    /**
     * Test attribute "skew_margin"
     */
    public function testPropertySkewMargin()
    {
    }

    /**
     * Test attribute "station_box_angle"
     */
    public function testPropertyStationBoxAngle()
    {
    }
}
