<?php
/**
 * SVNL3BGPTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iVantage API
 *
 * This is the iDirect iVantage API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SVNL3BGPTest Class Doc Comment
 *
 * @category    Class
 * @description SVNL3BGP
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SVNL3BGPTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SVNL3BGP"
     */
    public function testSVNL3BGP()
    {
    }

    /**
     * Test attribute "remote_id"
     */
    public function testPropertyRemoteId()
    {
    }

    /**
     * Test attribute "as"
     */
    public function testPropertyAs()
    {
    }

    /**
     * Test attribute "enabled"
     */
    public function testPropertyEnabled()
    {
    }

    /**
     * Test attribute "orf"
     */
    public function testPropertyOrf()
    {
    }

    /**
     * Test attribute "route_redistribution"
     */
    public function testPropertyRouteRedistribution()
    {
    }

    /**
     * Test attribute "route_maps"
     */
    public function testPropertyRouteMaps()
    {
    }

    /**
     * Test attribute "aggregate_addresses"
     */
    public function testPropertyAggregateAddresses()
    {
    }

    /**
     * Test attribute "config_tables"
     */
    public function testPropertyConfigTables()
    {
    }

    /**
     * Test attribute "peers"
     */
    public function testPropertyPeers()
    {
    }

    /**
     * Test attribute "peer_groups"
     */
    public function testPropertyPeerGroups()
    {
    }
}
