<?php
/**
 * SVNL3Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iVantage API
 *
 * This is the iDirect iVantage API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SVNL3Test Class Doc Comment
 *
 * @category    Class
 * @description SVNL3
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SVNL3Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SVNL3"
     */
    public function testSVNL3()
    {
    }

    /**
     * Test attribute "eth0_ip_address"
     */
    public function testPropertyEth0IpAddress()
    {
    }

    /**
     * Test attribute "eth0_subnet_mask"
     */
    public function testPropertyEth0SubnetMask()
    {
    }

    /**
     * Test attribute "sat0_ip_address"
     */
    public function testPropertySat0IpAddress()
    {
    }

    /**
     * Test attribute "sat0_subnet_mask"
     */
    public function testPropertySat0SubnetMask()
    {
    }

    /**
     * Test attribute "bgp"
     */
    public function testPropertyBgp()
    {
    }
}
