<?php
/**
 * SVNL3BGPRouteRedistributionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iVantage API
 *
 * This is the iDirect iVantage API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SVNL3BGPRouteRedistributionTest Class Doc Comment
 *
 * @category    Class */
// * @description SVNL3BGPRouteRedistribution
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SVNL3BGPRouteRedistributionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SVNL3BGPRouteRedistribution"
     */
    public function testSVNL3BGPRouteRedistribution()
    {
    }

    /**
     * Test attribute "static_routes_enabled"
     */
    public function testPropertyStaticRoutesEnabled()
    {
    }

    /**
     * Test attribute "connected_routes_enabled"
     */
    public function testPropertyConnectedRoutesEnabled()
    {
    }

    /**
     * Test attribute "rip_routes_enabled"
     */
    public function testPropertyRipRoutesEnabled()
    {
    }
}
