<?php
/**
 * VLanInfoDNSTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iVantage API
 *
 * This is the iDirect iVantage API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * VLanInfoDNSTest Class Doc Comment
 *
 * @category    Class
 * @description VLanInfoDNS
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VLanInfoDNSTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "VLanInfoDNS"
     */
    public function testVLanInfoDNS()
    {
    }

    /**
     * Test attribute "enabled"
     */
    public function testPropertyEnabled()
    {
    }

    /**
     * Test attribute "primary_name"
     */
    public function testPropertyPrimaryName()
    {
    }

    /**
     * Test attribute "primary_addr"
     */
    public function testPropertyPrimaryAddr()
    {
    }

    /**
     * Test attribute "secondary_name"
     */
    public function testPropertySecondaryName()
    {
    }

    /**
     * Test attribute "secondary_addr"
     */
    public function testPropertySecondaryAddr()
    {
    }

    /**
     * Test attribute "cache_size"
     */
    public function testPropertyCacheSize()
    {
    }

    /**
     * Test attribute "fwd_q_size"
     */
    public function testPropertyFwdQSize()
    {
    }

    /**
     * Test attribute "fwd_timeout"
     */
    public function testPropertyFwdTimeout()
    {
    }
}
