<?php
/**
 * VLanInfoDHCPTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iVantage API
 *
 * This is the iDirect iVantage API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * VLanInfoDHCPTest Class Doc Comment
 *
 * @category    Class
 * @description VLanInfoDHCP
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VLanInfoDHCPTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "VLanInfoDHCP"
     */
    public function testVLanInfoDHCP()
    {
    }

    /**
     * Test attribute "dhcp_id"
     */
    public function testPropertyDhcpId()
    {
    }

    /**
     * Test attribute "lease_seconds"
     */
    public function testPropertyLeaseSeconds()
    {
    }

    /**
     * Test attribute "dhcp_mode"
     */
    public function testPropertyDhcpMode()
    {
    }

    /**
     * Test attribute "primary_dns_addr"
     */
    public function testPropertyPrimaryDnsAddr()
    {
    }

    /**
     * Test attribute "secondary_dns_addr"
     */
    public function testPropertySecondaryDnsAddr()
    {
    }

    /**
     * Test attribute "default_gw_addr"
     */
    public function testPropertyDefaultGwAddr()
    {
    }

    /**
     * Test attribute "relay_server"
     */
    public function testPropertyRelayServer()
    {
    }

    /**
     * Test attribute "client_addr_ranges"
     */
    public function testPropertyClientAddrRanges()
    {
    }
}
