<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iVantage API
 *
 * This is the iDirect iVantage API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for applicationservicegroupApplicationservicegroupIdGet
     *
     * .
     *
     */
    public function testApplicationservicegroupApplicationservicegroupIdGet()
    {
    }

    /**
     * Test case for applicationservicegroupApplicationservicegroupIdPatch
     *
     * .
     *
     */
    public function testApplicationservicegroupApplicationservicegroupIdPatch()
    {
    }

    /**
     * Test case for applicationservicegroupGet
     *
     * .
     *
     */
    public function testApplicationservicegroupGet()
    {
    }

    /**
     * Test case for authorizePost
     *
     * .
     *
     */
    public function testAuthorizePost()
    {
    }

    /**
     * Test case for bucBucIdGet
     *
     * .
     *
     */
    public function testBucBucIdGet()
    {
    }

    /**
     * Test case for bucGet
     *
     * .
     *
     */
    public function testBucGet()
    {
    }

    /**
     * Test case for carrierCarrierIdDelete
     *
     * .
     *
     */
    public function testCarrierCarrierIdDelete()
    {
    }

    /**
     * Test case for carrierCarrierIdGet
     *
     * .
     *
     */
    public function testCarrierCarrierIdGet()
    {
    }

    /**
     * Test case for carrierCarrierIdPatch
     *
     * .
     *
     */
    public function testCarrierCarrierIdPatch()
    {
    }

    /**
     * Test case for carrierGet
     *
     * .
     *
     */
    public function testCarrierGet()
    {
    }

    /**
     * Test case for carrierPost
     *
     * .
     *
     */
    public function testCarrierPost()
    {
    }

    /**
     * Test case for downconverterDownconverterIdDelete
     *
     * .
     *
     */
    public function testDownconverterDownconverterIdDelete()
    {
    }

    /**
     * Test case for downconverterDownconverterIdGet
     *
     * .
     *
     */
    public function testDownconverterDownconverterIdGet()
    {
    }

    /**
     * Test case for downconverterDownconverterIdPatch
     *
     * .
     *
     */
    public function testDownconverterDownconverterIdPatch()
    {
    }

    /**
     * Test case for downconverterGet
     *
     * .
     *
     */
    public function testDownconverterGet()
    {
    }

    /**
     * Test case for downconverterPost
     *
     * .
     *
     */
    public function testDownconverterPost()
    {
    }

    /**
     * Test case for hubrftGet
     *
     * .
     *
     */
    public function testHubrftGet()
    {
    }

    /**
     * Test case for hubrftHubrftIdDelete
     *
     * .
     *
     */
    public function testHubrftHubrftIdDelete()
    {
    }

    /**
     * Test case for hubrftHubrftIdGet
     *
     * .
     *
     */
    public function testHubrftHubrftIdGet()
    {
    }

    /**
     * Test case for hubrftHubrftIdPatch
     *
     * .
     *
     */
    public function testHubrftHubrftIdPatch()
    {
    }

    /**
     * Test case for hubrftPost
     *
     * .
     *
     */
    public function testHubrftPost()
    {
    }

    /**
     * Test case for inroutegroupGet
     *
     * .
     *
     */
    public function testInroutegroupGet()
    {
    }

    /**
     * Test case for inroutegroupInroutegroupIdDelete
     *
     * .
     *
     */
    public function testInroutegroupInroutegroupIdDelete()
    {
    }

    /**
     * Test case for inroutegroupInroutegroupIdGet
     *
     * .
     *
     */
    public function testInroutegroupInroutegroupIdGet()
    {
    }

    /**
     * Test case for inroutegroupInroutegroupIdPatch
     *
     * .
     *
     */
    public function testInroutegroupInroutegroupIdPatch()
    {
    }

    /**
     * Test case for inroutegroupPost
     *
     * .
     *
     */
    public function testInroutegroupPost()
    {
    }

    /**
     * Test case for linecardGet
     *
     * .
     *
     */
    public function testLinecardGet()
    {
    }

    /**
     * Test case for linecardLinecardIdDelete
     *
     * .
     *
     */
    public function testLinecardLinecardIdDelete()
    {
    }

    /**
     * Test case for linecardLinecardIdGet
     *
     * .
     *
     */
    public function testLinecardLinecardIdGet()
    {
    }

    /**
     * Test case for linecardLinecardIdPatch
     *
     * .
     *
     */
    public function testLinecardLinecardIdPatch()
    {
    }

    /**
     * Test case for linecardPost
     *
     * .
     *
     */
    public function testLinecardPost()
    {
    }

    /**
     * Test case for lnbGet
     *
     * .
     *
     */
    public function testLnbGet()
    {
    }

    /**
     * Test case for lnbLnbIdGet
     *
     * .
     *
     */
    public function testLnbLnbIdGet()
    {
    }

    /**
     * Test case for networkGet
     *
     * .
     *
     */
    public function testNetworkGet()
    {
    }

    /**
     * Test case for networkNetworkIdDelete
     *
     * .
     *
     */
    public function testNetworkNetworkIdDelete()
    {
    }

    /**
     * Test case for networkNetworkIdGet
     *
     * .
     *
     */
    public function testNetworkNetworkIdGet()
    {
    }

    /**
     * Test case for networkNetworkIdPatch
     *
     * .
     *
     */
    public function testNetworkNetworkIdPatch()
    {
    }

    /**
     * Test case for networkPost
     *
     * .
     *
     */
    public function testNetworkPost()
    {
    }

    /**
     * Test case for protocolprocessorGet
     *
     * .
     *
     */
    public function testProtocolprocessorGet()
    {
    }

    /**
     * Test case for protocolprocessorPost
     *
     * .
     *
     */
    public function testProtocolprocessorPost()
    {
    }

    /**
     * Test case for protocolprocessorProtocolprocessorIdDelete
     *
     * .
     *
     */
    public function testProtocolprocessorProtocolprocessorIdDelete()
    {
    }

    /**
     * Test case for protocolprocessorProtocolprocessorIdGet
     *
     * .
     *
     */
    public function testProtocolprocessorProtocolprocessorIdGet()
    {
    }

    /**
     * Test case for protocolprocessorProtocolprocessorIdPatch
     *
     * .
     *
     */
    public function testProtocolprocessorProtocolprocessorIdPatch()
    {
    }

    /**
     * Test case for remoteGet
     *
     * .
     *
     */
    public function testRemoteGet()
    {
    }

    /**
     * Test case for remotePost
     *
     * .
     *
     */
    public function testRemotePost()
    {
    }

    /**
     * Test case for remoteRemoteIdAddRoamingInstancePost
     *
     * .
     *
     */
    public function testRemoteRemoteIdAddRoamingInstancePost()
    {
    }

    /**
     * Test case for remoteRemoteIdApplyChangesPatch
     *
     * .
     *
     */
    public function testRemoteRemoteIdApplyChangesPatch()
    {
    }

    /**
     * Test case for remoteRemoteIdDelete
     *
     * .
     *
     */
    public function testRemoteRemoteIdDelete()
    {
    }

    /**
     * Test case for remoteRemoteIdGet
     *
     * .
     *
     */
    public function testRemoteRemoteIdGet()
    {
    }

    /**
     * Test case for remoteRemoteIdPatch
     *
     * .
     *
     */
    public function testRemoteRemoteIdPatch()
    {
    }

    /**
     * Test case for remoteRemoteIdRawOptionsfileGet
     *
     * .
     *
     */
    public function testRemoteRemoteIdRawOptionsfileGet()
    {
    }

    /**
     * Test case for remoteRemoteIdResetPatch
     *
     * .
     *
     */
    public function testRemoteRemoteIdResetPatch()
    {
    }

    /**
     * Test case for remoteRemoteIdStatusGet
     *
     * .
     *
     */
    public function testRemoteRemoteIdStatusGet()
    {
    }

    /**
     * Test case for remoteRemoteIdStopCwPnPatch
     *
     * .
     *
     */
    public function testRemoteRemoteIdStopCwPnPatch()
    {
    }

    /**
     * Test case for remoteRemoteIdTxCwPatch
     *
     * .
     *
     */
    public function testRemoteRemoteIdTxCwPatch()
    {
    }

    /**
     * Test case for remoteRemoteIdTxPnPatch
     *
     * .
     *
     */
    public function testRemoteRemoteIdTxPnPatch()
    {
    }

    /**
     * Test case for remoteservicegroupGet
     *
     * .
     *
     */
    public function testRemoteservicegroupGet()
    {
    }

    /**
     * Test case for remoteservicegroupRemoteservicegroupIdGet
     *
     * .
     *
     */
    public function testRemoteservicegroupRemoteservicegroupIdGet()
    {
    }

    /**
     * Test case for remoteservicegroupRemoteservicegroupIdPatch
     *
     * .
     *
     */
    public function testRemoteservicegroupRemoteservicegroupIdPatch()
    {
    }

    /**
     * Test case for spacecraftGet
     *
     * .
     *
     */
    public function testSpacecraftGet()
    {
    }

    /**
     * Test case for spacecraftPost
     *
     * .
     *
     */
    public function testSpacecraftPost()
    {
    }

    /**
     * Test case for spacecraftSpacecraftIdDelete
     *
     * .
     *
     */
    public function testSpacecraftSpacecraftIdDelete()
    {
    }

    /**
     * Test case for spacecraftSpacecraftIdGet
     *
     * .
     *
     */
    public function testSpacecraftSpacecraftIdGet()
    {
    }

    /**
     * Test case for spacecraftSpacecraftIdPatch
     *
     * .
     *
     */
    public function testSpacecraftSpacecraftIdPatch()
    {
    }

    /**
     * Test case for teleportGet
     *
     * .
     *
     */
    public function testTeleportGet()
    {
    }

    /**
     * Test case for teleportPost
     *
     * .
     *
     */
    public function testTeleportPost()
    {
    }

    /**
     * Test case for teleportTeleportIdDelete
     *
     * .
     *
     */
    public function testTeleportTeleportIdDelete()
    {
    }

    /**
     * Test case for teleportTeleportIdGet
     *
     * .
     *
     */
    public function testTeleportTeleportIdGet()
    {
    }

    /**
     * Test case for teleportTeleportIdPatch
     *
     * .
     *
     */
    public function testTeleportTeleportIdPatch()
    {
    }

    /**
     * Test case for upconverterGet
     *
     * .
     *
     */
    public function testUpconverterGet()
    {
    }

    /**
     * Test case for upconverterPost
     *
     * .
     *
     */
    public function testUpconverterPost()
    {
    }

    /**
     * Test case for upconverterUpconverterIdDelete
     *
     * .
     *
     */
    public function testUpconverterUpconverterIdDelete()
    {
    }

    /**
     * Test case for upconverterUpconverterIdGet
     *
     * .
     *
     */
    public function testUpconverterUpconverterIdGet()
    {
    }

    /**
     * Test case for upconverterUpconverterIdPatch
     *
     * .
     *
     */
    public function testUpconverterUpconverterIdPatch()
    {
    }

    /**
     * Test case for userGet
     *
     * .
     *
     */
    public function testUserGet()
    {
    }

    /**
     * Test case for userPost
     *
     * .
     *
     */
    public function testUserPost()
    {
    }

    /**
     * Test case for userUserIdGet
     *
     * .
     *
     */
    public function testUserUserIdGet()
    {
    }

    /**
     * Test case for userUserIdPatch
     *
     * .
     *
     */
    public function testUserUserIdPatch()
    {
    }
}
